const nameDisplayers = document.querySelectorAll(".nameDisplayer");

const emailDisplayer = document.getElementById("emailDisplayer");

const ticketAvatar = document.getElementById("ticketAvatar");

const ticketName = document.getElementById("ticketName");

const ticketGithub = document.getElementById("ticketGithub");

const ticketNumber = document.getElementById("ticketNumber");

// When Java backend finishes processing the POST request, it should return a JSON object that looks like this:
// {
//   "name": "Jonatan Kristof",
//   "email": "jonatan@email.com",
//   "github": "@jonatankristof0101",
//   "avatarUrl": "./path/to/uploaded/image.jpg", 
//   "ticketNumber": "01609"
// }
//  avatarUrl could be a URL to where Java saved the image, or a base64 string.
//  ticketNumber was generated by backend.

export default function buildTicket (ticketData) {

    nameDisplayers.forEach(displayer => displayer.textContent = ticketData.name);
    
    emailDisplayer.textContent = ticketData.email;

    ticketAvatar.src = ticketData.avatarUrl;

    ticketName.textContent = ticketData.name;

    ticketGithub.textContent = await validateGitHub(ticketData.github);

    ticketNumber.textContent = `#${ticketData.ticketNumber}`;
}